/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dukendev

import dukendev.day1.PuzzleOne
import kotlin.test.Test
import kotlin.test.assertEquals

class TestPuzzle1 {


    @Test
    fun parseNumeralsTest() {
        val puzzleOne = PuzzleOne()
        assertEquals(Pair(7, 7), puzzleOne.parseNumerals("treb7uchet"))
        assertEquals(Pair(1, 5), puzzleOne.parseNumerals("a1b2c3d4e5f"))
    }

    @Test
    fun exampleSumTest() {
        val testInput = listOf(
            "1abc2", "pqr3stu8vwx", "a1b2c3d4e5f", "treb7uchet"
        )
        val puzzleOne = PuzzleOne()
        assertEquals(142, puzzleOne.getSumOfCalibrationValues(testInput))
    }




}
