/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dukendev

import java.io.File


fun main() {
    val file = File("/Users/sanjeetyadav/dev/advent-of-code-2023/app/src/main/kotlin/dukendev/day1/part1.txt")
    println(file.readLines())
    println("Hello, Advent of Code 2023")
}
